apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deploy
  labels:
    app: python-api
spec:
  selector:
    matchLabels:
      app: python-api
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        image: teambd3/python-api:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
