# set base image (host OS)
FROM python:3.10

# Adding trusting keys to apt for repositories
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

# Adding Google Chrome to the repositories
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

# Updating apt to see and install Google Chrome
RUN apt-get -y update

# Magic happens
RUN apt-get install -y google-chrome-stable
# # Installing Unzip
# RUN apt-get install -yqq unzip

# # Download the Chrome Driver
# RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/` curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE `/chromedriver_linux64.zip

# # Unzip the Chrome Driver into /usr/local/bin directory
# RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

# # Set display port as an environment variable
# ENV DISPLAY=:99


# set the working directory in the container
RUN mkdir -p /app
WORKDIR /app


# copy the dependencies file to the working directory
COPY ./src/requirements.txt /app/requirements.txt

# install dependencies
RUN pip install -r requirements.txt
# RUN pip uninstall Flask Jinja2
# RUN pip install Flask Jinja2

# copy the content of the local src directory to the working directory
COPY ./src/ /app/

# ENV FLASK_APP=server.py

# CMD flask run -h 0.0.0.0 -p 5000

# command to run on container start
CMD [ "python","-u", "main.py" ]