# set base image (host OS)
FROM python:3.10


# set the working directory in the container
RUN mkdir -p /app
WORKDIR /app


# copy the dependencies file to the working directory
COPY ./src/requirements.txt /app/requirements.txt

# install dependencies
RUN pip install -r requirements.txt
# RUN pip uninstall Flask Jinja2
# RUN pip install Flask Jinja2

# copy the content of the local src directory to the working directory
COPY ./src/ /app/

ENV FLASK_APP=server.py

CMD flask run -h 0.0.0.0 -p 5000

# command to run on container start
#CMD [ "python", "main.py" ]